/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import userinterface.CustomerRole.*;
import Business.EcoSystem;
import Business.Order;
import Business.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ninoshka
 */
public class AssignDeliveryManJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    
    Order order;
    EcoSystem business;
    /**
     * Creates new form RequestLabTestJPanel
     */
    public AssignDeliveryManJPanel(JPanel userProcessContainer, Order order,EcoSystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        
        this.order = order;
        this.business=business;
        populateComboBox();
       
    }

   public void  populateComboBox(){
        DefaultComboBoxModel dm=new DefaultComboBoxModel();
           for(Organization o:business.getDeliveryManDirectory().getOrganizationList()){
             for(UserAccount u:o.getUserAccountDirectory().getUserAccountList())  {
         
           dm.addElement(u); 
             }
   }
       deliveryAgentComboBox.setModel(dm);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * JComboBox<String> seatsComboBox;
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestdeliveryJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        deliveryAgentComboBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(153, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestdeliveryJButton.setBackground(new java.awt.Color(153, 153, 153));
        requestdeliveryJButton.setText("Assign Order");
        requestdeliveryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestdeliveryJButtonActionPerformed(evt);
            }
        });
        add(requestdeliveryJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, 40));

        jLabel1.setText("Select a delivery agent:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 130, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 120, 30));

        deliveryAgentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryAgentComboBoxActionPerformed(evt);
            }
        });
        add(deliveryAgentComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 220, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestdeliveryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestdeliveryJButtonActionPerformed
  UserAccount selectedItem = (UserAccount) deliveryAgentComboBox.getSelectedItem();
        
        if (selectedItem == null){
            return;
        }
        order.setStatus("assigned");
        order.setDeliveryManName(selectedItem.getEmployee().getName());  
        order.setDeliveryManUserName(selectedItem.getUsername()); 
        order.setDeliveryManId(selectedItem.getEmployee().getId()); 
        JOptionPane.showMessageDialog(null, "Delivery man assigned successfully");
         return ; 
        
        
    }//GEN-LAST:event_requestdeliveryJButtonActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void deliveryAgentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryAgentComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deliveryAgentComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> deliveryAgentComboBox;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton requestdeliveryJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
